import type { LocaleMessages } from "@/types/i18n";

const ita: LocaleMessages = {
  header: {
    title: "Gestore Attività",
    home: "Home",
    login: "Accedi",
    signup: "Registrati",
    logout: "Esci",
    language: "Lingua:",
  },
  taskList: {
    addTask: "Aggiungi attività",
    noTaskFound: "Nessuna attività trovata",
    taskFilt: "Nessuna task con queste caratteristiche è stata trovata",
    noTask: "Nessuna task trovata",
    addMess: "Inizia ad aggiungere una nuova task!",
    modal: {
      titleCreate: "Crea una nuova attività",
      title: "Titolo Task",
      titleEdit: "Modifica l'attività",
      titleView: "Visualizza l'attività",
      okTitleSave: "Salva",
      closeModal: "chiudi",
      titleValidate: "Titolo non valido, deve contenere meno di 50 caratteri",
      descriptionValidate:
        "Descrizione non valida, deve contenere meno di 200 caratteri",
      dueDate: "Da terminare entro",
      taskCancelTitle: "Annulla",
      deleteTaskMessage: "Sei sicuro di voler eliminare questa attività?",
      deleteTaskTitle: "Conferma eliminazione",
      deleteTaskOkTitle: "Sì, elimina",
      editTaskMessage: "Sei sicuro di voler modificare questa attività?",
      edit: "modifica",
      editTaskTitle: "Conferma modifica",
      editTaskOkTitle: "Modifica",
      addTaskMessage: "Sei sicuro di voler creare questa attività?",
      addTaskTitle: "Conferma creazione",
      addTaskOkTitle: "Crea",
      titleRequired: "è obbligatorio.",
      allFieldsRequired: "Tutti i campi sono obbligatori",
      description: "Descrizione",
      selectStatus: "Stato",
      selectPriority: "Priorità",
      formValidationError: "Per favore compila tutti i campi obbligatori",
      confirm: "Conferma",
      cancel: "Annulla",
    },
    toast: {
      toastDeleteMessage: "Attività eliminata!",
      toastEditMessage: "Attività modificata!",
      toastAddMessage: "Attività aggiunta!",
      toastErrorDelete: "Errore durante l'eliminazione della task",
      toastErrorModify: "Errore durante il salvataggio",
      toastErrorAdd: "Errore durante la creazione della task",
      toastCreate: "Compila tutti i campi",
      toastDate: "Data non valida",
    },
  },
  taskFilter: {
    filterHeaderMessage: "Filtra le attività:",
    status: "Stato: ",
    priority: "Priorità:",
    startDate: "INIZIO:",
    dueDate: "Data di scadenza",
    endDate: "FINE:",
    addTask: "Aggiungi Attività",
    dateLabel: "SELEZIONA",
    orderBy: "Ordina per:",
    clearBtn: "Cancella",
    sortByPriority: "Ordina per priorità",
    removeDate: "Cancella date",
    resetSort: "Resetta ordinamento",
    sortByDueDate: "Ordina per scadenza",
    ascending: "Ascendente",
    descending: "Discendente",
    clearFilter: "elimina filtri",
    mobileTitle: "Filtri",
    statusFilter: {
      inProgress: "IN CORSO",
      completed: "COMPLETATO",
      pending: "IN ATTESA",
    },
    priorityFilter: {
      low: "BASSA",
      medium: "MEDIA",
      high: "ALTA",
      urgent: "URGENTE",
    },
  },
  baseTask: {
    title: "Titolo:",
    priority: "Priorità:",
    status: "Stato: ",
    description: "Descrizione:",
    completition: "Da completare entro: ",
    button: {
      modify: "Modifica",
      delete: "Elimina",
    },
    createdOn: "Creato il: ",
  },
  signupForm: {
    messagges: "Crea il tuo Account",
    email: "Email",
    username: "Nome utente",
    placeholderName: "Inserisci nome utente",
    usernameInvalid:
      "Nome utente non valido, deve contenere almeno 3 caratteri e massimo 32",
    usernameRequired: "username obbligatorio",
    password: "Password",
    placeholderPassword: "Inserisci la password",
    passwordRequired: "Password obbligatoria",
    signupError: "Registrazione fallita. Riprova più tardi",
    passwordInvalid:
      "password non valida, deve contenere almeno 8 caratteri e massimo 20",
    signup: "Registrati",
    alreadyRegistered: "Sei già registrato? Accedi!",
    login: "Accedi ora",
    emailInvalid: "Inserisci un indirizzo email valido (esempio@gmail.com).",
    emailExample: "nome@example.com",
  },
  loginForm: {
    messagges: "Entra nel tuo account",
    username: "Nome utente",
    usernameRequired: "Username obbligatorio",
    usernameInvalid:
      "Nome utente non valido,deve contenere almeno 8 caratteri e massimo 20",
    placeholderName: "Inserisci nome utente",
    loginError: "il server non risponde",
    password: "Password",
    placeholderPassword: "Inserisci la password",
    passwordRequired: "Password obbligatoria",
    passwordInvalid:
      "password non valida, deve contenere almeno 8 caratteri e massimo 20",
    login: "Accedi",
    notAlreadyRegistered: "Registrati se non hai un account!",
    signup: "Registrati",
    invalidCredentials: "Nome utente o password non validi.",
  },
};

export default ita;
