import type { LocaleMessages } from "@/types/i18n";

const ita: LocaleMessages = {
  header: {
    title: "Gestore Attività",
    home: "Home",
    login: "Accedi",
    signup: "Registrati",
    logout: "Esci",
    language: "Lingua:",
  },
  taskList: {
    addTask: "Aggiungi attività",
    noTaskFound: "Nessuna attività trovata",
    modal: {
      titleCreate: "Crea una nuova attività",
      titleEdit: "Modifica l'attività",
      titleView: "Visualizza l'attività",
      okTitleSave: "Salva",
      dueDate: "Da terminare entro",
      taskCancelTitle: "Annulla",
      deleteTaskMessage: "Sei sicuro di voler eliminare questa attività?",
      deleteTaskTitle: "Conferma eliminazione",
      deleteTaskOkTitle: "Sì, elimina",
      editTaskMessage: "Sei sicuro di voler modificare questa attività?",
      editTaskTitle: "Conferma modifica",
      editTaskOkTitle: "Modifica",
      addTaskMessage: "Sei sicuro di voler creare questa attività?",
      addTaskTitle: "Conferma creazione",
      addTaskOkTitle: "Crea",
      titleRequired: "è obbligatorio.",
      allFieldsRequired: "Tutti i campi sono obbligatori",
      description: "Inserisci la descrizione dell'attività",
      selectStatus: "Seleziona uno stato",
      selectPriority: "Seleziona una priorità",
      formValidationError: "Per favore compila tutti i campi obbligatori",
    },
    toast: {
      toastDeleteMessage: "Attività eliminata!",
      toastEditMessage: "Attività modificata!",
      toastAddMessage: "Attività aggiunta!",
    },
    popover: {
      message: "Clicca per visualizzare più dettagli",
    },
  },
  taskFilter: {
    filterHeaderMessage: "Filtra le attività:",
    status: "Stato: ",
    priority: "Priorità:",
    startDate: "Inizio:",
    endDate: "Fine:",
    orderBy: "Ordina per:",
    clearBtn: "Cancella",
    sortByPriority: "Ordina per priorità",
    sortByDueDate: "Ordina per scadenza",
    ascending: "Ascendente",
    descending: "Discendente",
    clearFilter: "elimina filtri",
    statusFilter: {
      inProgress: "IN CORSO",
      completed: "COMPLETATO",
      pending: "IN ATTESA",
    },
    priorityFilter: {
      low: "BASSA",
      medium: "MEDIA",
      high: "ALTA",
      urgent: "URGENTE",
    },
  },
  baseTask: {
    title: "Titolo:",
    priority: "Priorità:",
    status: "Stato: ",
    description: "Descrizione:",
    completition: "Da completare entro: ",
    button: {
      modify: "Modifica",
      delete: "Elimina",
    },
    createdOn: "Creato il: ",
  },
  signupForm: {
    messagges: "Crea il tuo Account",
    email: "Email",
    username: "Nome utente",
    placeholderName: "Inserisci nome utente",
    usernameInvalid: "Nome utente non valido, deve contenere almeno 3 caratteri e massimo 32",
    usernameRequired: "username obbligatorio",
    password: "Password",
    placeholderPassword: "Inserisci la password",
    passwordRequired: "Password obbligatoria",
    passwordInvalid:
      "password non valida, deve contenere almeno 8 caratteri e massimo 20",
    signup: "Registrati",
    alreadyRegistered: "Sei già registrato? Accedi!",
    login: "Accedi ora",
    emailInvalid: "Inserisci un indirizzo email valido (esempio@gmail.com).",
    emailExample: "nome@example.com",
  },
  loginForm: {
    messagges: "Entra nel tuo account",
    username: "Nome utente",
    usernameRequired: "Username obbligatorio",
    usernameInvalid: "Nome utente non valido (almeno 6 caratteri, massimo 32)",
    placeholderName: "Inserisci nome utente",
    password: "Password",
    placeholderPassword: "Inserisci la password",
    passwordRequired: "Password obbligatoria",
    passwordInvalid:
      "Incorrect password (must be at least 8 characters long and maximum 20)",
    login: "Accedi",
    notAlreadyRegistered: "Registrati se non hai un account!",
    signup: "Registrati",
    invalidCredentials: "Nome utente o password non validi.",
  },
};

export default ita;
