/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./components/ui/BaseCard.vue')['default']
    BaseTask: typeof import('./components/ui/BaseTask.vue')['default']
    MainPage: typeof import('./components/pages/MainPage.vue')['default']
    Pages: typeof import('./components/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./components/pages/SignUp.vue')['default']
    TaskFilter: typeof import('./components/filter/TaskFilter.vue')['default']
    TaskList: typeof import('./components/pages/TaskList.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    UserAuth: typeof import('./components/pages/UserAuth.vue')['default']
  }
}
